export type {ConsentGate} from "./config/consent";
export {ALLOW_ALL_CONSENT, applyConsent, bothConsent, consentFor} from "./config/consent";
export {projectData} from "./config/fieldProjection";
export type {FieldSelection, ProbeConfig, ProbeOverride} from "./config/probeConfig";
export {applyConfig, DEFAULT_PROBE_CONFIG, mergeConfigs} from "./config/probeConfig";
export type {CollectOptions, DeviceIntelOptions, RawSignalEvent} from "./DeviceIntel";
export {DeviceIntel} from "./DeviceIntel";
export type {DeviceIdentity, OsIntegritySignals} from "./NativeDeviceIntel";
export {androidOnly, iosOnly} from "./probes/platformProbe";
export type {RuntimeSignals} from "./probes/runtimeProbe";
export type {Probe, ProbeOutcome, ProbeResult} from "./probes/types";
export type {WireEnvelope} from "./transport/envelope";
export {serializePlaintext} from "./transport/envelope";
export type {TransportConfig} from "./transport/transport";
