package com.reactnativedeviceintel

// NativeDeviceIntelSpec is generated by codegen into THIS package (react { codegenJavaPackageName =
// "com.reactnativedeviceintel" } in android/build.gradle), so it's referenced same-package with no
// import. It is NOT under com.facebook.fbreact.specs.
import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import java.util.concurrent.Executors

/**
 * Thin dispatch layer: each Spec method resolves the corresponding provider's raw signal map, or
 * rejects with a stable error code the JS probe framework surfaces as `{status:"error"}` without
 * failing sibling probes. No signal fusion / verdict logic lives here — providers return raw fields.
 */
class DeviceIntelModule(reactContext: ReactApplicationContext) :
  NativeDeviceIntelSpec(reactContext) {

  private val deviceInfo = DeviceInfoProvider(reactContext)
  private val application = ApplicationInfoProvider(reactContext)
  private val hardware = HardwareInfoProvider(reactContext)
  private val osIntegrity = OsIntegrityProvider(reactContext)
  private val fridaScan = FridaScanProvider()
  private val network = NetworkInfoProvider(reactContext)
  private val telephony = TelephonyInfoProvider(reactContext)
  private val locale = LocaleInfoProvider(reactContext)
  private val geolocation = GeolocationInfoProvider(reactContext)
  private val mediaBluetoothApps = MediaBluetoothAppsInfoProvider(reactContext)
  private val gpuBenchmark = GpuBenchmarkProvider()
  private val audioLatency = AudioLatencyProvider(reactContext)

  override fun getDeviceIdentity(promise: Promise) {
    resolveOrReject(promise, "getDeviceIdentity") { deviceInfo.getDeviceIdentity() }
  }

  override fun getHardwareSignals(promise: Promise) {
    resolveOrReject(promise, "getHardwareSignals") { hardware.getHardwareSignals() }
  }

  override fun getFontsFingerprint(promise: Promise) {
    resolveOrReject(promise, "getFontsFingerprint") { hardware.getFontsFingerprint() }
  }

  override fun getApplicationSignals(promise: Promise) {
    resolveOrReject(promise, "getApplicationSignals") { application.getApplicationSignals() }
  }

  override fun getOsIntegrity(promise: Promise) {
    resolveOrReject(promise, "getOsIntegrity") { osIntegrity.getOsIntegrity() }
  }

  override fun getFridaScanSignals(promise: Promise) {
    resolveOrReject(promise, "getFridaScanSignals") { fridaScan.getFridaScanSignals() }
  }

  override fun getForkJailbreakSignal(promise: Promise) {
    // Android stub: the fork()-based jailbreak check is an iOS-only probe. The JS `os_integrity_fork_test`
    // probe is androidOnly-disabled, so this is never called on Android; implemented for Spec parity.
    resolveOrReject(promise, "getForkJailbreakSignal") {
      Arguments.createMap().apply { putBoolean("testPerformed", false) }
    }
  }

  override fun getNetworkSignals(promise: Promise) {
    resolveOrReject(promise, "getNetworkSignals") { network.getNetworkSignals() }
  }

  override fun getTelephonySignals(promise: Promise) {
    resolveOrReject(promise, "getTelephonySignals") { telephony.getTelephonySignals() }
  }

  override fun getLocaleSignals(promise: Promise) {
    resolveOrReject(promise, "getLocaleSignals") { locale.getLocaleSignals() }
  }

  override fun getGeolocationSignals(promise: Promise) {
    resolveOrReject(promise, "getGeolocationSignals") { geolocation.getGeolocationSignals() }
  }

  override fun getMediaBluetoothAppsSignals(promise: Promise) {
    resolveOrReject(promise, "getMediaBluetoothAppsSignals") { mediaBluetoothApps.getMediaBluetoothAppsSignals() }
  }

  override fun getGpuBenchmark(promise: Promise) {
    resolveOrReject(promise, "getGpuBenchmark") { gpuBenchmark.getGpuBenchmark() }
  }

  override fun getAudioLatency(promise: Promise) {
    resolveOrReject(promise, "getAudioLatency") { audioLatency.getAudioLatency() }
  }

  // Each probe runs on its own background thread so the probes the JS framework fires in parallel
  // actually execute concurrently. RN dispatches native-module methods serially on a single thread,
  // so without this every probe queued behind a slow one (frida socket connect, package audit,
  // /proc scans) blows its short per-probe JS timeout while merely waiting its turn — the exact
  // reason only the first probe (device_identity) succeeded and every other one reported "timeout".
  // Providers are stateless per call, so concurrent invocation is safe. Daemon threads + a cached
  // pool (idle threads reaped after 60s) mean no explicit lifecycle teardown is required.
  private val probeExecutor =
    Executors.newCachedThreadPool { runnable ->
      Thread(runnable, "device-intel-probe").apply { isDaemon = true }
    }

  private fun resolveOrReject(promise: Promise, code: String, block: () -> Any) {
    probeExecutor.execute {
      try {
        promise.resolve(block())
      } catch (e: Exception) {
        promise.reject(code, e)
      }
    }
  }

  companion object {
    const val NAME = NativeDeviceIntelSpec.NAME
  }
}
